spring:
  application:
    name: wzd_api_gateway

server:
  port: 8000

#ribbon:
#  eureka:
#    enabled: false
    
zuul:
  routes:
    backend-service:
      path: /backend/**
      url: http://127.0.0.1:18080/backend/

#shuaicj.security.jwt.secret: otherpeopledontknowit
