server:
  port: 18090
  servlet:
    context-path: /backend2

spring:
  redis:
    # 임베디드용 설정
    host: localhost
    port: 26379
    # Object 설정
    database: 0
    timeout: 50
  profiles:
    active: local

  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2_db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 1234
    schema: classpath:/scheme.sql

  messages:
    #    always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
    #    cache-duration: # Loaded resource bundle files cache duration. When not set, bundles are cached forever. If a duration suffix is not specified, seconds will be used.
    basename: i18n/server-global-messages,i18n/server-messages,i18n/validation-messages,i18n/excelheader-messages
    encoding: UTF-8 # Message bundles encoding.
    fallback-to-system-locale: false

  multi-datasource:
    readonly:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password: 1234
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-idle: 20
      max-wait: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      validation-query: 'SELECT 1'
      validation-query-timeout: 3
      validation-interval: 3000
    readwrite:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password: 1234
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-idle: 20
      max-wait: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      validation-query: 'SELECT 1'
      validation-query-timeout: 3
      validation-interval: 3000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: password

  # JSP설정
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
 # datasource:
 #   driver-class-name: com.mysql.cj.jdbc.Driver
 #   url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&characterEncoding=UTF-8
 #   username: sa
 #   password: password
 # redis:
 #   host: localhost
 #   port: 12379





 ## mybatis.config-location=classpath:mybatis-config.xml
 ## mybatis.mapper-locations=classpath:mappers/*.xm



#mybatis:
#  config-location: classpath:mapper/mybatis-config.xml
#  mapper-locations: classpath:mapper/**/*Mapper.xml
##  config: classpath:mapper/mybatis-config.xml
##  mapper: classpath:mapper/**/*Mapper.xml


